app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
naoned_oai_pmh_server:
    resource: "@NaonedOaiPmhServerBundle/Resources/config/routing.yml"
    prefix:   /OaiPmh
    
recolnat_darwin_core:
    resource: "@RecolnatDarwinCoreBundle/Resources/config/routing.yml"
    prefix:   /recolnat
   