# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        cas:
            id: prayno.cas_user_provider
#        in_memory:
#            memory:
#                users:
#                    mhnaix:
#                        password: 123456
#                        roles: 'ROLE_USER'

    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
#            logout: true
            guard:
                authenticators:
                    - prayno.cas_authenticator
#            form_login:
#                login_path: login
#                check_path: login
#                default_target_path: index
            logout:
                path:   /logout
                target: /userlogout

#
    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

