# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    dwc.extractor:
            class: Recolnat\DarwinCoreBundle\Component\Extractor

    naoned.oaipmh.data_provider:
            class: Recolnat\DarwinCoreBundle\OaiPmh\OaiDwcDataProvider
            calls:
                - [ setContainer, [@service_container] ]
            arguments: ["@dwc.extractor"]