services:
    appbundle.doctrine.dbal.events.oracle_session_init.listener:
        class: %doctrine.dbal.events.oracle_session_init.class%
        tags:
            - { name: doctrine.event_listener, event: postConnect, connection: default }
            - { name: doctrine.event_listener, event: postConnect, connection: diff }

    appbundle.doctrine.dbal.oracle_platform.type_mapping.listener:
        class: AppBundle\Listener\OracleDoctrineTypeMappingListener
        tags:
            - { name: doctrine.event_listener, event: postConnect, connection: default }
            - { name: doctrine.event_listener, event: postConnect, connection: diff }
