<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Business\User\User;
use AppBundle\Entity\Collection;
use Doctrine\ORM\AbstractQuery;

/**
 * BibliographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliographyRepository extends AbstractRecolnatRepository
{
    /**
     * @param Collection $collection
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderFindByCollection(Collection $collection)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('b.referenceid as id')
            ->from('AppBundle\Entity\Bibliography', 'b')
            ->join('b.specimen', 's')
            ->andWhere('s.collection = :collection')
            ->setParameter('collection', $collection);
    }

    /**
     *
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('b')
            ->from('AppBundle\Entity\Bibliography', 'b', 'b.referenceid')
            ->andWhere($qb->expr()->in('b.referenceid', $ids));
        $qb->setParameter('ids', $ids, 'rawid');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param string $id
     * @param int    $fetchMode
     * @return array|object|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneById($id, $fetchMode = AbstractQuery::HYDRATE_OBJECT)
    {
        return $this->getQueryFindOneById('bibliography', $id)->getOneOrNullResult($fetchMode);
    }

    /**
     * @param string $id
     * @return array|object|null
     */
    public function findOneByIdToArray($id)
    {
        return $this->findOneById($id, AbstractQuery::HYDRATE_ARRAY);
    }

    /**
     *
     * @param array $specimenCodes
     * @return \Doctrine\Common\Collections\Collection
     */
    public function findBySpecimenCodeUnordered($specimenCodes)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('b')
            ->from('AppBundle\Entity\Bibliography', 'b')
            ->join('b.specimen', 's');
        $this->setSpecimenCodesWhereClause($qb, $specimenCodes);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param Collection $collection
     * @param array      $specimenCodes
     * @param int        $hydratationMode
     * @return array
     */
    public function findBySpecimenCodes(Collection $collection, $specimenCodes, $hydratationMode = AbstractQuery::HYDRATE_ARRAY)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('b')
            ->from('AppBundle\Entity\Bibliography', 'b')
            ->addSelect($this->getExprConcatSpecimenCode().' as specimencode')
            ->join('b.specimen', 's');
        $this->setSpecimenCodesWhereClause($collection, $qb, $specimenCodes);

        return $this->orderResultSetBySpecimenCode($qb->getQuery()->getResult($hydratationMode), 'referenceid');
    }

    /**
     * @param array  $datas
     * @param string $id
     * @return mixed
     */
    public function update(array $datas, $id)
    {
        $qb = $this->createUpdateQuery($datas);

        $qb->where('a.referenceid = HEXTORAW(:id)')
            ->setParameter('id', $id);

        return $qb->getQuery()->execute();
    }
}
