<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Collection;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\Query\Expr\Join;

/**
 * DeterminationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeterminationRepository extends RecolnatRepositoryAbstract
{
    /**
     * @param Collection $collection
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderFindByCollection(Collection $collection)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('d')
            ->from('AppBundle\Entity\Determination', 'd')
            ->join('d.specimen', 's')
            ->andWhere('s.collection = :collection')
            ->setParameter('collection', $collection);
    }

    /**
     *
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('d')
            ->from('AppBundle\Entity\Determination', 'd', 'd.identificationid')
            ->andWhere($qb->expr()->in('d.identificationid', $ids));
        $qb->setParameter('ids', $ids, 'rawid');
        return $qb->getQuery()->getResult();
    }

    /**
     * @param array $id
     * @param int   $fetchMode
     * @return array|object|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneById($id, $fetchMode = AbstractQuery::HYDRATE_OBJECT)
    {
        return $this->getQueryFindOneById($id)->getOneOrNullResult($fetchMode);
    }

    /**
     * @param $id
     * @return array|null
     */
    public function findOneByIdToArray($id)
    {

        return $this->findOneById($id, AbstractQuery::HYDRATE_ARRAY);
    }

    /**
     * @param array  $id
     * @param string $field
     * @return object|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneFieldById($id, $field)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('d.'.$field)
            ->from('AppBundle\Entity\Determination', 'd', 'd.identificationid')
            ->where('d.identificationid = :id')
            ->setParameter('id', $id, 'rawid');
        return $qb->getQuery()->getArrayResult();
    }
    /**
     * @param $id
     * @return \Doctrine\ORM\Query
     */
    private function getQueryFindOneById($id)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('d')
            ->from('AppBundle\Entity\Determination', 'd', 'd.identificationid')
            ->where('d.identificationid = :id')
            ->setParameter('id', $id, 'rawid')
            ->getQuery();
    }

    /**
     *
     * @param array $specimenCodes
     * @return \Doctrine\Common\Collections\Collection
     */
    public function findBySpecimenCodeUnordered($specimenCodes)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('d')
            ->join('d.specimen', 's');
        $this->setSpecimenCodesWhereClause($qb, $specimenCodes);
        return $qb->getQuery()->getResult();
    }

    /**
     *
     * @param array $specimenCodes
     * @return array
     */
    public function findBySpecimenCodes($specimenCodes)
    {
        $qb = $this->createQueryBuilder('d');

        $qb
            ->select('d')
            ->addSelect($this->getExprConcatSpecimenCode().' as specimencode')
            ->join('d.specimen', 's');
        $this->setSpecimenCodesWhereClause($qb, $specimenCodes);
        return $this->orderResultSetBySpecimenCode($qb->getQuery()->getResult(), 'identificationid');
    }

    /**
     *
     * @param string $occurrenceId
     * @return \AppBundle\Entity\Determination | null
     */
    public function findBestDetermination($occurrenceId)
    {
        $qb = $this->createQueryBuilder('d');

        $qb
            ->select('d')
            ->join('AppBundle\Entity\Specimen', 's', Join::WITH, 's.occurrenceid = :occurrenceid');
        $qb->setParameter('occurrenceid', $occurrenceId, 'rawid');
        return $this->orderResultSetBySpecimenCode($qb->getQuery()->getOneOrNullResult(), 'identificationid');
    }
}
