<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\Query\Expr\Join ;
/**
 * DeterminationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeterminationRepository extends RecolnatRepositoryAbstract
{
//    public function find($id) {
//        $query = $this->getEntityManager()->createQueryBuilder()
//                ->select('d')
//                ->addSelect('bin2hex(occurrenceid)', 'occurrenceid')
//                ->from('AppBundle\Entity\Determination', 'd')
//                ->where('identificationid = :identificationid')
//                ->setParameter('identificationid', $id)
//                ->getQuery() ;
//        return $query->getResult() ;
//    }
    /**
     * 
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('d')
                ->from('AppBundle\Entity\Determination', 'd', 'd.identificationid')
                ->where('d.identificationid IN (\''.implode('\',\'', $ids).'\')')
                ->getQuery() ;
        return $query->getResult() ;
    }
    
    /**
     * 
     * @param array $specimenCodes
     * @return array
     */
    public function findBySpecimenCodes($specimenCodes)
    {
        $qb = $this->createQueryBuilder('d');
        
        $query = $qb
                ->select('d')
                ->addSelect($this->getExprConcatSpecimenCode($qb).' as specimenid')
                ->join('AppBundle\Entity\Specimen', 's', Join::WITH);
        $query->add('where', $qb->expr()->in($this->getExprConcatSpecimenCode($qb), ':specimenCodes'));
        $query->setParameter('specimenCodes', $specimenCodes);
        return $this->orderResultSetBySpecimenId($query->getQuery()->getResult()) ;
    }
    
    /**
     * 
     * @param rawid $occurrenceId
     * @return \AppBundle\Entity\Determination | null
     */
    public function findBestDetermination($occurrenceId)
    {
        $qb = $this->createQueryBuilder('d');
        
        $query = $qb
                ->select('d')
                ->join('AppBundle\Entity\Specimen', 's', Join::WITH, 's.occurrenceid = :occurrenceid');
        $query->setParameter('occurrenceid', $occurrenceId);
        return $this->orderResultSetBySpecimenId($query->getQuery()->getOneOrNullResult()) ;
    }
}
