<?php

namespace AppBundle\Entity\Repository;

/**
 * LocalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalisationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('l')
                ->from('AppBundle\Entity\Localisation', 'l', 'l.locationid')
                ->where('l.locationid IN (:ids)')
                ->setParameter('ids', $ids)
                ->getQuery() ;
        return $query->getResult() ;
    }
}
