<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\AbstractQuery;

/**
 * MultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultimediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByIdToArray($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('m')
            ->from('AppBundle\Entity\Multimedia', 'm', 'm.multimediaid')
            ->where('m.multimediaid = :id')
            ->setParameter('id', $id)
            ->getQuery();
        return $query->getOneOrNullResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
