<?php

namespace AppBundle\Entity\Repository;

/**
 * NumPicturaeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumPicturaeRepository extends \Doctrine\ORM\EntityRepository
{
}
