<?php

namespace AppBundle\Entity\Repository;

/**
 * RecolteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecolteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('r')
                ->from('AppBundle\Entity\Recolte', 'r', 'r.eventid')
                ->where('r.eventid IN (\''.implode('\',\'', $ids).'\')')
                ->getQuery() ;
        return $query->getResult() ;
    }
}
