<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * SpecimenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecimenRepository extends RecolnatRepositoryAbstract
{
    /**
     * 
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('s')
                ->from('AppBundle\Entity\Specimen', 's', 's.occurrenceid')
                ->where('s.occurrenceid IN (\''.implode('\',\'', $ids).'\')')
                ->getQuery() ;
        return $query->getResult() ;
    }
    public function findOneById($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('s')
                ->from('AppBundle\Entity\Specimen', 's', 's.occurrenceid')
                ->where('s.occurrenceid = :id')
                ->setParameter('id', $id)
                ->getQuery() ;
        return $query->getOneOrNullResult();
    }
    /**
     * 
     * @param string $specimenCode
     * @return \AppBundle\Entity\Specimen
     */
    public function findOneBySpecimenCodes($specimenCode)
    {
        $qb = $this->createQueryBuilder('s');
        
        $query = $qb
                ->select('s');
                
        $qb->add('where', $qb->expr()->in($this->getExprConcatSpecimenCode($qb), ':specimenCode'));
        $qb->setParameter('specimenCode', $specimenCode);
        return $query->getQuery()->getOneOrNullResult();
    }
    /**
     * 
     * @param array $specimenCodes
     * @return array
     */
    public function findBySpecimenCodes($specimenCodes)
    {
        $qb = $this->createQueryBuilder('s');
        
        $query = $qb
                ->select('s')
                ->addSelect($this->getExprConcatSpecimenCode($qb).' as specimenid');
        $qb->add('where', $qb->expr()->in($this->getExprConcatSpecimenCode($qb), ':specimenCodes'));
        $qb->setParameter('specimenCodes', $specimenCodes);
        return $this->orderResultSetBySpecimenId($query->getQuery()->getResult(), 'occurrenceid') ;
    }

    /**
     * 
     * @param array $specimenCodes
     * @return array
     */
    public function getQueryForSpecimenCodes($specimenCodes)
    {
        $qb = $this->createQueryBuilder('s');
        
        $query = $qb
                ->select('s')
        ->add('where', $qb->expr()->in($this->getExprConcatSpecimenCode($qb), ':specimenCodes'));
        $qb->setParameter('specimenCodes', $specimenCodes);
        return $query->getQuery();
    }
}
