<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\Query\Expr\Join ;
/**
 * StratigraphyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StratigraphyRepository extends RecolnatRepositoryAbstract
{
    /**
     * 
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('s')
                ->from('AppBundle\Entity\Stratigraphy', 's', 's.geologicalcontextid')
                ->where('s.geologicalcontextid IN (:ids)')
                ->setParameter('ids', $ids)
                ->getQuery() ;
        return $query->getResult() ;
    }
    
    public function findOneById($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('s')
                ->from('AppBundle\Entity\Stratigraphy', 's', 's.geologicalcontextid')
                ->where('s.geologicalcontextid = :id')
                ->setParameter('id', $id)
                ->getQuery() ;
        return $query->getOneOrNullResult();
    }

    /**
     * 
     * @param array $specimenCodes
     * @return array
     */
    public function findBySpecimenCodes($specimenCodes)
    {
        $qb = $this->createQueryBuilder('st');
        
        $query = $qb
                ->select('st')
                ->addSelect($this->getExprConcatSpecimenCode($qb).' as specimenid')
                ->join('AppBundle\Entity\Specimen', 's', Join::WITH);
        $qb->add('where', $qb->expr()->in($this->getExprConcatSpecimenCode($qb), ':specimenCodes'));
        $qb->setParameter('specimenCodes', $specimenCodes);
        return $this->orderResultSetBySpecimenId($query->getQuery()->getResult(), 'geologicalcontextid') ;
    }
}
