<?php

namespace AppBundle\Entity\Repository;

/**
 * StratigraphyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StratigraphyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('s')
                ->from('AppBundle\Entity\Stratigraphy', 's', 's.geologicalcontextid')
                ->where('s.geologicalcontextid IN (:ids)')
                ->setParameter('ids', $ids)
                ->getQuery() ;
        return $query->getResult() ;
    }
}
