<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * TaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonRepository extends RecolnatRepositoryAbstract
{
    /**
     * 
     * @param array $ids
     * @return array
     */
    public function findById($ids)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('t')
                ->from('AppBundle\Entity\Taxon', 't', 't.taxonid')
                ->where('t.taxonid IN (\''.implode('\',\'', $ids).'\')')
                ->getQuery();
        return $query->getResult();
    }
    public function findOneById($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
                ->select('t')
                ->from('AppBundle\Entity\Taxon', 't', 't.taxonid')
                ->where('t.taxonid = :id')
                ->setParameter('id', $id)
                ->getQuery();
        return $query->getOneOrNullResult();
    }
    /**
     * 
     * @param array $specimenCodes
     * @return \Doctrine\Common\Collections\Collection
     */
    public function findBySpecimenCodeUnordered($specimenCodes)
    {
        $qb = $this->createQueryBuilder('t');
        
        $query = $qb
            ->select('t')
            ->innerJoin('t.determination', 'd')
            ->innerJoin('d.specimen', 's', \Doctrine\ORM\Query\Expr\Join::WITH, 
                    $qb->expr()->in($this->getExprConcatSpecimenCode($qb), ':specimenCodes'));
        $query->setParameter('specimenCodes', $specimenCodes);
        return $query->getQuery()->getResult();
    }
    /**
     * 
     * @param array $specimenCodes
     * @return array
     */
    public function findBySpecimenCodes($specimenCodes)
    {
        $qb = $this->createQueryBuilder('t');
        
        $query = $qb
            ->select('t')
            ->addSelect($this->getExprConcatSpecimenCode($qb).' as specimencode')
            ->innerJoin('t.determination', 'd')
            ->innerJoin('d.specimen', 's', \Doctrine\ORM\Query\Expr\Join::WITH, $qb->expr()->in($this->getExprConcatSpecimenCode($qb), ':specimenCodes'));
        $query->setParameter('specimenCodes', $specimenCodes);
        return $this->orderResultSetBySpecimenCode($query->getQuery()->getResult(), 'taxonid');
    }
    
    public function findBestTaxon($occurrenceId) {
        $qb = $this->createQueryBuilder('t');
        $query = $qb
                ->select('t')
                ->innerJoin('t.determination', 'd')
                ->where('d.specimen = :occurrenceid')
                ->setParameter('occurrenceid', $occurrenceId)
                ->setMaxResults(1)
                ->orderBy('d.identificationverifstatus', 'DESC');
        return $query->getQuery()->getOneOrNullResult();
    }
    
    public function findBestTaxonsBySpecimenCode($specimenCode) {
        $qb = $this->createQueryBuilder('t');
        $query = $qb
                ->select('t')
                ->innerJoin('t.determination', 'd')
                ->innerJoin('d.specimen', 's', \Doctrine\ORM\Query\Expr\Join::WITH, $qb->expr()->in($this->getExprConcatSpecimenCode($qb), ':specimenCode'))
                ->setMaxResults(1)
                ->orderBy('d.identificationverifstatus', 'DESC');
        $query->setParameter('specimenCode', $specimenCode);
        return $query->getQuery()->getOneOrNullResult();
    }
}
