services:
    diff.stats:
        class: AppBundle\Manager\DiffStatsManager
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
    diff.manager:
        class: AppBundle\Manager\DiffManager
        arguments:
            em: "@doctrine.orm.entity_manager"
            statsManager: "@diff.stats"
            exportPath: "%export_path%"
            
            
    diff.specimens:
        class: AppBundle\Manager\DiffSpecimens
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
    diff.bibliographies:
        class: AppBundle\Manager\DiffBibliographies
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
    diff.determinations:
        class: AppBundle\Manager\DiffDeterminations
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
    diff.localisations:
        class: AppBundle\Manager\DiffLocalisations
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
    diff.recoltes:
        class: AppBundle\Manager\DiffRecoltes
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
    diff.stratigraphies:
        class: AppBundle\Manager\DiffStratigraphies
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
    diff.taxons:
        class: AppBundle\Manager\DiffTaxons
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"

#    specimenManager:
#        class: AppBundle\Manager\SpecimenManager
#        arguments:
#            emR: "@doctrine.orm.entity_manager"
#            emD: "@doctrine.orm.diff_entity_manager"
#            translator: "@translator"
    specimenService:
        class: AppBundle\Services\ServiceSpecimen
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
            sessionManager: "@session"
            diffManager: "@diff.manager"
            maxItemPerPage: "%knp_paginator.page_range%"
            
    genericEntityManager:
        class: AppBundle\Manager\GenericEntityManager
        arguments:
            emR: "@doctrine.orm.entity_manager"
            emD: "@doctrine.orm.diff_entity_manager"
            translator: "@translator"
    exportManager:
        class: AppBundle\Manager\ExportManager
        arguments:
            export_path: "%export_path%"
            sessionManager: "@session"
            genericEntityManager: "@genericEntityManager"
            
    # TWIG EXTENSIONS
    app.twig_multimedia_extension:
        class: AppBundle\Twig\MultimediaExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_specimen_extension:
        class: AppBundle\Twig\SpecimenExtension
        arguments:
            doctrine: "@doctrine"
            translator: "@translator"
        public: false
        tags:
            - { name: twig.extension }
    app.twig_export_extension:
        class: AppBundle\Twig\ExportExtension
        public: false
        tags:
            - { name: twig.extension }
            
    # LISTENERS
    appBundle.flash_messenger:
        class: AppBundle\Listener\FlashMessagesListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.response}
