services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Manager\DiffComputer:
#        class: AppBundle\Manager\DiffComputer
        arguments:
#            - '@doctrine'
            $maxNbSpecimenPerPass: "%max_nb_specimen_par_pass%"
#            - "@logger"
        tags:
            - { name: monolog.handler, channel: compute }
        public: true

    AppBundle\Manager\DiffManager:
#        class: AppBundle\Manager\DiffManager
        arguments:
#            managerRegistry: "@doctrine"
            $recolnatAlias: "%database_user%"
            $recolnatBufferAlias: "%database_user_diff%"
        public: true

    AppBundle\Manager\GenericEntityManager:
#        class: AppBundle\Manager\GenericEntityManager
        arguments:
#            managerRegistry: "@doctrine"
            $maxNbSpecimenPerPass: "%max_nb_specimen_par_pass%"
#            logger : "@logger"
        tags:
            - { name: monolog.handler, channel: compute }

    AppBundle\Manager\ExportManager:
#        class: AppBundle\Manager\ExportManager
        public: true
        arguments:
#            managerRegistry: "@doctrine"
#            sessionManager: "@session"
#            genericEntityManager: "@genericentitymanager"
            $maxItemPerPage: "%knp_paginator.page_range%"
#            diffComputer: "@diff.computer"
            $userGroup: "%user_group%"
#            logger : "@logger"
        tags:
            - { name: monolog.handler, channel: compute }

    AppBundle\Business\StatsManager:
        class: AppBundle\Business\StatsManager
        public: true
#        arguments:
#            exportManager: "@exportmanager"

    AppBundle\Manager\UtilityService:
#        class: AppBundle\Manager\UtilityService
        public: true
#            managerRegistry: "@doctrine"
#            translator: "@translator"

    # TWIG EXTENSIONS
    app.twig_multimedia_extension:
        class: AppBundle\Twig\MultimediaExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_specimen_extension:
        class: AppBundle\Twig\SpecimenExtension
        arguments:
#            doctrine: "@doctrine"
#            translator: "@translator"
#            sessionManager: "@session"
            $urlRecolnat: "%url_recolnat%"
        public: false
        tags:
            - { name: twig.extension }
    app.twig_export_extension:
        class: AppBundle\Twig\ExportExtension
        public: false
        tags:
            - { name: twig.extension }
            
    # LISTENERS
    app.flash_messenger:
        class: AppBundle\Listener\FlashMessagesListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.response}

    # Security
    app.security.recolnat_user_provider:
        class: AppBundle\Security\RecolnatUserProvider
        arguments:
            - "%export_path%"
            - "%api_recolnat_base_uri%"
            - "%api_recolnat_user_path%"
            - "%user_group%"

    # Command
    command.search_diffs:
        class: AppBundle\Command\SearchDiffCommand
        tags:
            -  { name: console.command }
        arguments:
            - "%server_login_url%"
            - "%api_recolnat_server_ticket_path%"
            - "%request_options%"
            - "%api_recolnat_base_uri%"
            - "%api_recolnat_user_path%"

    command.compute_diffs:
        class: AppBundle\Command\ComputeDiffCommand
        tags:
            -  { name: console.command }

    command.export_diffs:
        class: AppBundle\Command\ExportCommand
        tags:
            -  { name: console.command }
        arguments:
            $serverLoginUrl: "%server_login_url%"
            $serverTicket: "%api_recolnat_server_ticket_path%"
            $requestOptions: "%request_options%"
            $apiRecolnatBaseUri: "%api_recolnat_base_uri%"
            $apiRecolnatUserPath: "%api_recolnat_user_path%"
#            - "@genericentitymanager"
            $maxNbSpecimenPerPass: "%max_nb_specimen_par_pass%"

    command.harvest_data:
            class: AppBundle\Command\HarvestDataCommand
            tags:
                -  { name: console.command }
#            arguments:
#                genericEntityManager: "@genericentitymanager"
