services:
    diff.computer:
        class: AppBundle\Manager\DiffComputer
        arguments:
            managerRegistry: "@doctrine"
    diff.manager:
        class: AppBundle\Manager\DiffManager
        arguments:
            managerRegistry: "@doctrine"
            statsManager: "@diff.computer"
            exportPath: "%export_path%"

    genericEntityManager:
        class: AppBundle\Manager\GenericEntityManager
        arguments:
            managerRegistry: "@doctrine"
            translator: "@translator"

    exportManager:
        class: AppBundle\Manager\ExportManager
        arguments:
            export_path: "%export_path%"
            sessionManager: "@session"
            genericEntityManager: "@genericEntityManager"
            diffManager: "@diff.manager"
            maxItemPerPage: "%knp_paginator.page_range%"
    userManager:
        class: AppBundle\Business\User\User
        arguments:
            export_path: "%export_path%"
            maxItemPerPage: "%knp_paginator.page_range%"

    statsManager:
        class: AppBundle\Business\StatsManager
        arguments:
            exportManager: "@exportmanager"
            
    # TWIG EXTENSIONS
    app.twig_multimedia_extension:
        class: AppBundle\Twig\MultimediaExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_specimen_extension:
        class: AppBundle\Twig\SpecimenExtension
        arguments:
            doctrine: "@doctrine"
            translator: "@translator"
        public: false
        tags:
            - { name: twig.extension }
    app.twig_export_extension:
        class: AppBundle\Twig\ExportExtension
        public: false
        tags:
            - { name: twig.extension }
            
    # LISTENERS
    appBundle.flash_messenger:
        class: AppBundle\Listener\FlashMessagesListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.response}
