services:
    diff.computer:
        class: AppBundle\Manager\DiffComputer
        arguments:
            managerRegistry: "@doctrine"
            maxNbSpecimenPerPass: "%max_nb_specimen_par_pass%"
#    diff.manager:
#        class: AppBundle\Manager\OldDiffManager
#        arguments:
#            managerRegistry: "@doctrine"
#            recolnat_alias: "%database_user%"
#            recolnat_diff_alias: "%database_user_diff%"

    diff.manager:
        class: AppBundle\Manager\DiffManager
        arguments:
            managerRegistry: "@doctrine"
            recolnatAlias: "%database_user%"
            recolnatBufferAlias: "%database_user_diff%"

    genericentitymanager:
        class: AppBundle\Manager\GenericEntityManager
        arguments:
            managerRegistry: "@doctrine"

    exportmanager:
        class: AppBundle\Manager\ExportManager
        arguments:
            managerRegistry: "@doctrine"
            sessionManager: "@session"
            genericEntityManager: "@genericentitymanager"
            maxItemPerPage: "%knp_paginator.page_range%"
            diffComputer: "@diff.computer"
            userGroup: "%user_group%"

    statsmanager:
        class: AppBundle\Business\StatsManager
        arguments:
            exportManager: "@exportmanager"

    utility:
        class: AppBundle\Manager\UtilityService
        arguments:
            managerRegistry: "@doctrine"

    # TWIG EXTENSIONS
    app.twig_multimedia_extension:
        class: AppBundle\Twig\MultimediaExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig_specimen_extension:
        class: AppBundle\Twig\SpecimenExtension
        arguments:
            doctrine: "@doctrine"
            translator: "@translator"
            sessionManager: "@session"
            urlRecolnat: "%url_recolnat%"
        public: false
        tags:
            - { name: twig.extension }
    app.twig_export_extension:
        class: AppBundle\Twig\ExportExtension
        public: false
        tags:
            - { name: twig.extension }
            
    # LISTENERS
    app.flash_messenger:
        class: AppBundle\Listener\FlashMessagesListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.response}

    # Security
    app.security.recolnat_user_provider:
        class: AppBundle\Security\RecolnatUserProvider
        arguments:
            exportPath: "%export_path%"
            apiRecolnatBaseUri: "%api_recolnat_base_uri%"
            apiRecolnatUserPath: "%api_recolnat_user_path%"
            userGroup: "%user_group%"

    # Command
    command.search_diffs:
        class: AppBundle\Command\SearchDiffCommand
        tags:
            -  { name: console.command }
        arguments:
            serverLoginUrl: "%server_login_url%"
            serverTicket: "%api_recolnat_server_ticket_path%"
            requestOptions: "%request_options%"
            apiRecolnatBaseUri: "%api_recolnat_base_uri%"
            apiRecolnatUserPath: "%api_recolnat_user_path%"

    command.compute_diffs:
            class: AppBundle\Command\ComputeDiffCommand
            tags:
                -  { name: console.command }
