AppBundle\Entity\Bibliography:
    type: entity
    table: BIBLIOGRAPHIES
    repositoryClass: AppBundle\Entity\Repository\BibliographyRepository
    indexes:
        biblio_spec_idx_fk:
            columns:
                - OCCURRENCEID
        biblio_srcfileid_idx:
            columns:
                - SOURCEFILEID
    id:
        referenceid:
            type: guid
            nullable: false
            id: true
            column: REFERENCEID
            generator:
                strategy: SEQUENCE
    fields:
        bibliographiccitation:
            type: string
            nullable: true
            length: 1500
            options:
                fixed: false
            column: BIBLIOGRAPHICCITATION
        creator:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: CREATOR
        datePublication:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: DATE_PUBLICATION
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: DESCRIPTION
        identifier:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: IDENTIFIER
        language:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: LANGUAGE
        rights:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: RIGHTS
        source:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: SOURCE
        sourcefileid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: SOURCEFILEID
        subject:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: SUBJECT
        taxonremarks:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: TAXONREMARKS
        title:
            type: string
            nullable: true
            length: 600
            options:
                fixed: false
            column: TITLE
        type:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: TYPE
    manyToOne:
        occurrenceid:
            targetEntity: Specimen
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                OCCURRENCEID:
                    referencedColumnName: OCCURRENCEID
            orphanRemoval: false
    lifecycleCallbacks: {  }
