AppBundle\Entity\DownloadLog:
    type: entity
    table: DOWNLOAD_LOG
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: SEQUENCE
    fields:
        email:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: EMAIL
        eventDate:
            type: datetime
            nullable: true
            column: EVENT_DATE
        numberOfRecords:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: NUMBER_OF_RECORDS
        searchCriteria:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: SEARCH_CRITERIA
    lifecycleCallbacks: {  }
