AppBundle\Entity\Institution:
    type: entity
    table: INSTITUTIONS
    repositoryClass: AppBundle\Entity\Repository\InstitutionRepository
    indexes:
        institu_srcfileid_idx:
            columns:
                - SOURCEFILEID
    uniqueConstraints:
        institutioncode_unique_key:
            columns:
                - INSTITUTIONCODE
    id:
        institutionid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: INSTITUTIONID
            generator:
                strategy: SEQUENCE
    fields:
        institutioncode:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: INSTITUTIONCODE
        sourcefileid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: SOURCEFILEID
    lifecycleCallbacks: {  }
