AppBundle\Entity\Multimedia:
    type: entity
    table: MULTIMEDIA
    repositoryClass: AppBundle\Entity\Repository\MultimediaRepository
    indexes:
        multimedia_identifier_idx:
            columns:
                - IDENTIFIER
        media_srcfileid_idx:
            columns:
                - SOURCEFILEID
    id:
        multimediaid:
            type: guid
            nullable: false
            id: true
            column: MULTIMEDIAID
            generator:
                strategy: SEQUENCE
    fields:
        audience:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: AUDIENCE
        contributor:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CONTRIBUTOR
        created:
            type: datetime
            nullable: true
            options:
                default: sysdate
            column: CREATED
        creator:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CREATOR
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: DESCRIPTION
        discriminator:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: DISCRIMINATOR
        format:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: FORMAT
        identifier:
            type: string
            nullable: false
            length: 300
            options:
                fixed: false
            column: IDENTIFIER
        license:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LICENSE
        modified:
            type: datetime
            nullable: true
            column: MODIFIED
        publisher:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
                default: e-ReColNat
            column: PUBLISHER
        references:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: REFERENCES
        rights:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: RIGHTS
        rightsholder:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: RIGHTSHOLDER
        source:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: SOURCE
        sourcefileid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: SOURCEFILEID
        title:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: TITLE
        type:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: TYPE
    manyToMany:
        occurrenceid:
            targetEntity: Specimen
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: multimediaid
            joinTable:
                name: multimedia_has_occurrences
                joinColumns:
                    -
                        name: MULTIMEDIAID
                        referencedColumnName: MULTIMEDIAID
                inverseJoinColumns:
                    -
                        name: OCCURRENCEID
                        referencedColumnName: OCCURRENCEID
            orderBy: null
    lifecycleCallbacks: {  }
