AppBundle\Entity\Recolte:
    type: entity
    table: RECOLTES
    repositoryClass: AppBundle\Entity\Repository\RecolteRepository
    indexes:
        recolte_loca_idx_fk:
            columns:
                - LOCATIONID
        rec_srcfileid_idx:
            columns:
                - SOURCEFILEID
    id:
        eventid:
            type: guid
            nullable: false
            id: true
            column: EVENTID
            generator:
                strategy: SEQUENCE
    fields:
        decade:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DECADE
        eday:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: EDAY
        emonth:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: EMONTH
        eventdate:
            type: datetime
            nullable: true
            column: EVENTDATE
        eventremarks:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: EVENTREMARKS
        eyear:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: EYEAR
        fieldnotes:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: FIELDNOTES
        fieldnumber:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FIELDNUMBER
        habitat:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: HABITAT
        recordedby:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
            column: RECORDEDBY
        sday:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SDAY
        smonth:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SMONTH
        sourcefileid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: SOURCEFILEID
        syear:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SYEAR
        verbatimeventdate:
            type: datetime
            nullable: true
            column: VERBATIMEVENTDATE
    manyToOne:
        locationid:
            targetEntity: Localisation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                LOCATIONID:
                    referencedColumnName: LOCATIONID
            orphanRemoval: false
    lifecycleCallbacks: {  }
