AppBundle\Entity\Specimen:
    type: entity
    table: SPECIMENS
    repositoryClass: AppBundle\Entity\Repository\SpecimenRepository
    indexes:
        spec_strat_idx_fk:
            columns:
                - GEOLOGICALCONTEXTID
        spec_coll_idx_fk:
            columns:
                - COLLECTIONID
        spec_rec_idx_fk:
            columns:
                - EVENTID
        spec_srcfileid_idx:
            columns:
                - SOURCEFILEID
    id:
        occurrenceid:
            type: guid
            nullable: false
            id: true
            column: OCCURRENCEID
            generator:
                strategy: SEQUENCE
    fields:
        accessrights:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: ACCESSRIGHTS
        associatedmedia:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: ASSOCIATEDMEDIA
        associatedreferences:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: ASSOCIATEDREFERENCES
        associatedtaxa:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: ASSOCIATEDTAXA
        basisofrecord:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: BASISOFRECORD
        bibliographiccitation:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
            column: BIBLIOGRAPHICCITATION
        catalognumber:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: CATALOGNUMBER
        collectioncode:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
            column: COLLECTIONCODE
        created:
            type: datetime
            nullable: true
            column: CREATED
        disposition:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: DISPOSITION
        dwcaid:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: DWCAID
        hascoordinates:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: HASCOORDINATES
        hasmedia:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: HASMEDIA
        institutioncode:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: INSTITUTIONCODE
        lifestage:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: LIFESTAGE
        modified:
            type: datetime
            nullable: true
            column: MODIFIED
        occurrenceremarks:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: OCCURRENCEREMARKS
        ownerinstitutioncode:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: OWNERINSTITUTIONCODE
        recordnumber:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: RECORDNUMBER
        rights:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: RIGHTS
        rightsholder:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: RIGHTSHOLDER
        sex:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: SEX
        sourcefileid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: SOURCEFILEID
    manyToOne:
        collectionid:
            targetEntity: Collection
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                COLLECTIONID:
                    referencedColumnName: COLLECTIONID
            orphanRemoval: false
        geologicalcontextid:
            targetEntity: Stratigraphy
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                GEOLOGICALCONTEXTID:
                    referencedColumnName: GEOLOGICALCONTEXTID
            orphanRemoval: false
        eventid:
            targetEntity: Recolte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                EVENTID:
                    referencedColumnName: EVENTID
            orphanRemoval: false
    manyToMany:
        multimediaid:
            targetEntity: Multimedia
            cascade: {  }
            fetch: LAZY
            mappedBy: occurrenceid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
