AppBundle\Entity\Stratigraphy:
    type: entity
    table: STRATIGRAPHIES
    repositoryClass: AppBundle\Entity\Repository\StratigraphyRepository
    indexes:
        strat_srcfileid_idx:
            columns:
                - SOURCEFILEID
    id:
        geologicalcontextid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: GEOLOGICALCONTEXTID
            generator:
                strategy: SEQUENCE
    fields:
        bed:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: BED
        earliestageorloweststage:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: EARLIESTAGEORLOWESTSTAGE
        earliesteonorlowesteonothem:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: EARLIESTEONORLOWESTEONOTHEM
        earliestepochorlowestseries:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: EARLIESTEPOCHORLOWESTSERIES
        earliesteraorlowesterathem:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: EARLIESTERAORLOWESTERATHEM
        earliestperiodorlowestsystem:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: EARLIESTPERIODORLOWESTSYSTEM
        formation:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FORMATION
        group:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: GROUP_
        highestbiostratigraphiczone:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: HIGHESTBIOSTRATIGRAPHICZONE
        latestageorhigheststage:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LATESTAGEORHIGHESTSTAGE
        latesteonorhighesteonothem:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LATESTEONORHIGHESTEONOTHEM
        latestepochorhighestseries:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LATESTEPOCHORHIGHESTSERIES
        latesteraorhighesterathem:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LATESTERAORHIGHESTERATHEM
        latestperiodorhighestsystem:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LATESTPERIODORHIGHESTSYSTEM
        lowestbiostratigraphiczone:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: LOWESTBIOSTRATIGRAPHICZONE
        member:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MEMBER
        sourcefileid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: SOURCEFILEID
    lifecycleCallbacks: {  }
