AppBundle\Entity\UuidsForExport:
    type: entity
    table: UUIDS_FOR_EXPORT
    id:
        rnum:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: RNUM
            generator:
                strategy: SEQUENCE
    fields:
        occurrenceid:
            type: guid
            nullable: true
            column: OCCURRENCEID
    lifecycleCallbacks: {  }
